sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

before_install:
  - npm i npm@^4 -g
install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: npm run ci

after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && cat .coverage/lcovonly.info | ./node_modules/.bin/coveralls'
